### ISSUE TITLE
Compare tab displays "empty" colored rows

### ISSUE THREAD

**Issue by temmat** [fbarresi/TwinCatAdsTool#13]
The Compare tab doesn't display legible data - both when loading from a file or reading from a PLC. It seems it actually loads the data for comparison because there are colored rows displayed, but no actual data is visible.

Building and launching from source in debug mode produces numerous binding errors on this tab.
I haven't had the chance to check this further in depth. Will update if there is enough time.

**Comment by fbarresi** [comment]
Hi,
Can you please provide some example json you used for comparing?
Thanks

**Comment by temmat** [comment]
Sure. It doesn't depend on the json files thought from what I see. It appears the same if I read from PLC directly. Furthermore if I load the json files in the restore tab, they are displayed correctly (and can also be written to the PLC without problems). It's just the Compare tabs that doesn't show any text.

But anyway, find attached two files saved a couple of seconds apart. The only difference is some value that changes on the PLC.
In the compare tab (if I load them side by side) I can only see white rows and one gray row. I get that the coloring is correct to show the difference, but there is no data / text actually visible.

[Backup_2021-02-10-220102.json.txt](https://github.com/fbarresi/TwinCatAdsTool/files/5961542/Backup_2021-02-10-220102.json.txt)
[Backup_2021-02-10-220107.json.txt](https://github.com/fbarresi/TwinCatAdsTool/files/5961545/Backup_2021-02-10-220107.json.txt)

And the picture as it actually look

![Capture_TwincatADSToolCompare](https://user-images.githubusercontent.com/33503719/107572739-f6ae3d00-6bec-11eb-9498-095535c51a7b.PNG)

Same json loaded in the Restore tab

![Capture_TwincatADSToolRestore](https://user-images.githubusercontent.com/33503719/107572940-32490700-6bed-11eb-92da-4978a0a7423a.PNG)

I bet it's something obvious, but I haven't found the reason yet.

**Comment by temmat** [comment]
See the referenced pull request. Simple fix. Text was present, but not visible. Either increase the Height to something much bigger (something like 50 seems to be OK) or better yet specify the Padding to 0 as in the proposed pull request.

Best regards. 

#15

**Comment by fbarresi** [comment]
#15 fixed
