### ISSUE TITLE
Problem signature using program in PLC CX5120 Windows 7

### ISSUE THREAD

**Issue by elconfa** [fbarresi/TwinCatAdsTool#2]
Hello, I'm trying to start the program directly inside the PLC to point and read its variables, but the program gives me this error:

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	TwinCatAdsTool.exe
  Application Version:	1.0.0.0
  Application Timestamp:	ddb21eed
  Fault Module Name:	KERNELBASE.dll
  Fault Module Version:	6.1.7601.24540
  Fault Module Timestamp:	5ddf3fbb
  Exception Code:	e0434352
  Exception Offset:	0000845d
  OS Version:	6.1.7601.2.1.0.320.65
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

The OS PLC is Windows 7. How I can run this program?
Thanks
Massimo

**Comment by fbarresi** [comment]
Dear Massimo,

I think the problem could be in your operating system. 
I googled this error and it war reported 1 billion times on almost every architecture and windows version.

[The first reply here](https://answers.microsoft.com/en-us/windows/forum/windows_7-windows_programs/kernelbasedll-has-caused-my-applications-to-stop/b7e4738e-2f16-4a92-b00b-bc7c2dd50ce8) seems to solve the problem in many cases.

Which .Net Framework did you installed on your PLC? A wrong version of .Net can cause this effect as well. Please check that you are running v. 4.6.2 or newer.

Please let me know if/how you solved the problem.

**Comment by elconfa** [comment]
Hi, with your help I solved the problem. I installed Net Framework 4.7.1 and now it run without any problem.
Thanks

**Comment by fbarresi** [comment]
👍
