### ISSUE TITLE
Writing back a variable value of type TIME doesn't work

### ISSUE THREAD

**Issue by temmat** [fbarresi/TwinCatAdsTool#22]
Reading a persistant variable of type TIME works correctly (time value displayed is ok), but writing it back doesn't work.
There seems to be a problem with parsing the json string to the actual data type.

Error displayed is (example) "Error converting value "00:00:00.3000000" to type 'Twincat.PlcOpen.TIME',

(value readout is actually correct of T#300ms)

This occurs at least from version 1.1.48 and newer, haven't had the chance to check older.

**Comment by fbarresi** [comment]
Thank you for reporting!
That was a bug generated from the new handling for time variables in twincat.ads 5.
I'm going to fix it quick.
