### ISSUE TITLE
Project with 4200 persistent var, save to file an empty file

### ISSUE THREAD

**Issue by elconfa** [fbarresi/TwinCatAdsTool#3]
Hello, my project has "only" 4200 persistent variables, but after "Read from PLC" and "Save to file" the file created has only this result:
{}
Here is my project clean with only persistent Var.
I'm using TwinCat 4024.07

Thanks for your help
Massimo

[Backup_2020-02-21-091125.json.txt](https://github.com/fbarresi/TwinCatAdsTool/files/4234934/Backup_2020-02-21-091125.json.txt)

[CX5130-TwinCat_4024_07.tnzip.zip](https://github.com/fbarresi/TwinCatAdsTool/files/4235015/CX5130-TwinCat_4024_07.tnzip.zip)

**Comment by fbarresi** [comment]
Thank you for reporting this bug!

I fixed and tested with your example.
